### ISSUE TITLE
Dependency Geckolib crashes on launch when paired with Sodium

### ISSUE THREAD

**Issue by duncy** [raltsmc/desolation#1]
I'm not entirely sure if this is the correct etiquette, but I just wanted to post this in case anyone had this issue and thought it was this mod directly causing this issue.

It's not, and the owner of Geckolib is aware of this and plans to fix this issue in the next release.

See here:
https://github.com/bernie-g/geckolib/issues/26

**Comment by raltsmc** [comment]
Thanks for the heads-up, I added a notice to the mod description.

**Comment by bernie-g** [comment]
Just wanted to let you know that GeckoLib 3.0.0 for fabric is out and compatible with Sodium. It's also much more powerful than 2.0.0 and you should update if you have time. https://geckolib.com

**Comment by raltsmc** [comment]
Sorry it took me ages to get around to this. Version 1.0.4 now supports Geckolib 3.
