### ISSUE TITLE
Ash scuttlers get stuck when looking for ash

### ISSUE THREAD

**Issue by FewerFlaws** [raltsmc/desolation#11]
This little guy happily dug a couple cool things up for me but then got stuck when I pushed my luck on a third attempt.

![2021-01-31_22 54 18](https://user-images.githubusercontent.com/75643699/106424760-96164780-6417-11eb-96bd-f09d13dcb7aa.png)

**Comment by raltsmc** [comment]
Tried to address this in 1b787dd47c4d948676f5ceef25f1f3d3696b01e0, they should get stuck much less often now - let me know if you still notice any oddities.
