### ISSUE TITLE
Request: Active Charcoal Block

### ISSUE THREAD

**Issue by FewerFlaws** [raltsmc/desolation#17]
I'd like to use active charcoal to form the portal frame to another dimension in my modpack.  Would you be interested in adding an active charcoal block?  I created a texture for you to make it easy.  It's based on the vanilla coal texture, but darker and with a subtle red tint.

![sideBySide](https://user-images.githubusercontent.com/75643699/107112794-289b5a00-680f-11eb-94d6-b7b52ab2b5de.PNG)
Side by side with charcoal block texture

![active_coal_block](https://user-images.githubusercontent.com/75643699/107112795-2cc77780-680f-11eb-8f45-98cb83d8d7dd.png)
The texture itself

**Comment by raltsmc** [comment]
Looks good, will add it in the next update.
