### ISSUE TITLE
Game crashes on startup.

### ISSUE THREAD

**Issue by Mysteriaa** [raltsmc/desolation#18]
I'm using version 1.0.4.2 of Desolation. I tried disabling Sodium but it still crashes on startup. 
Crashlog:
[crash-2021-02-10_20.48.16-client.txt](https://github.com/raltsmc/desolation/files/5962763/crash-2021-02-10_20.48.16-client.txt)

**Comment by raltsmc** [comment]
Thanks for the report, should be fixed in 1.0.4.3!
