### ISSUE TITLE
Let charred sapling be obtained in survival somehow

### ISSUE THREAD

**Issue by saltyseadoggo** [raltsmc/desolation#27]
You may already have a plan for a way to obtain the charred sapling in survival, but I wanna voice my desire for this anyway. I use potted saplings to label the containers in my wood storage area in my current survival world, and I can't obtain a charred sapling for Desolation's charred wood type.
The obvious solution would be to have them drop from charred branches/leaves. If you don't want it to drop from leaves because you don't want the trees to be renewable, I suggest letting the saplings generate uncommonly throughout the biomes this mod adds. This way, if players want a few to decorate with, they're obtainable.
They'd also need a loot table so they can actually drop themselves when broken.

**Comment by raltsmc** [comment]
I wasn't sure how to implement the saplings in survival without making them renewable, but I like the idea of having a few randomly generate. I'll note that down for the next update.
